version: "3"

services:

   app:
      build:
         dockerfile: ./compose/local/Dockerfile
         context: .
      ports:
         - 8000:8000
      volumes:
         - .:/django/

   postgres:
      image: postgres
      volumes:
         - local_postgres_data:/var/lib/postgresql/data
         - local_postgres_data_backups:/backups
      env_file:
         - ./.envs/.local/.postgres

volumes:
   local_postgres_data:
   local_postgres_data_backups: